---
services:
  redis:
    image: redis/redis-stack:latest
  mailhog:
    image: mailhog/mailhog:latest
    ports: [ 1025:1025, 8025:8025 ]
  discourse:
    build: ./discourse
    ports: [ 3000:3000, 4200:4200 ]
