---
services:
  redis:
    image: redis/redis-stack:latest
  discourse:
    build: ./discourse
    ports: [ 3000:3000, 4200:4200 ]
  backend:
    build: ./backend
    volumes: [ ./backend:/app ]
    ports: [ 5001:5001 ]
  frontend:
    build: ./frontend
    volumes: [ ./frontend:/app ]
    ports: [ 8080:8080 ]
